# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: "kafka-connect-cluster"


bootstrapServers: nil
kafkaClusterName: nil